### ISSUE TITLE
Details (Overview of Route)

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#1]
**1. User story**

As a user I want to see the overview of a specific route on the details page.

Explanation: On the main page there is a list of flows and every flow has a view button. Currenly there is only general information shown about the flow, also information of endpoints (just like the edit page).

**1.1	Acceptance tests**

Check when clicking on the "View" button on the page, if a page is shown with all information about that
flow (should contain the same information as clicking on "Edit" button.
   
**1.2	Use case**

_Pre-condition_
	A flow is created
_Happy flow_
        User see page with detail of flows	
_Alternative path:_
	No

**1.3	Screen information**

Page: Main page (Flows)

**Comment by papicn** [comment]
Task implemented
