### ISSUE TITLE
Input Validation for URI field

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#10]
**1. User story**

User story: As a user I want to make sure that I have valid configuration for the URI field.

Explanation: If for example a user has a FILE production then a valid file path must be entered. 

For every supported component the URI as show at https://github.com/apache/camel/tree/master/components should be validated. Of course this depends on the component used.

You can use something like this validation:

https://github.com/yuyang041060120/ng2-validation
https://github.com/ianstormtaylor/superstruct

**1.1	Acceptance tests**

Check when user edits some input that isn't allow for uri syntax

**1.2	Use case**

Pre-condition:
	- a flow is created
Happy flow:
	- Valid syntax nothing is shown
Alternative path:
	Show validation errors next to the field.
	
**1.3	Screen information**

Main page (Flow edit page)

**Comment by papicn** [comment]
Task implemented
