### ISSUE TITLE
Removal of To Endpoints while editing a flow doesn't get saved

### ISSUE THREAD

**Issue by goran237** [assimbly/gateway#100]
**SUMMARY**
Flow has multi To endpoints. In edit mode, after removing all but one To endpoints and performing apply/save, no changes are saved in the flow itself

**STEPS TO REPRODUCE**
Flows Page
Find multi-To endpoint flow and edit the flow
Remove all but one To endpoint
Apply/Save

**ACTUAL RESULT**
In the flow, all the To endpoints are still there

**ATTACHMENTS**
https://elanwave-my.sharepoint.com/:v:/p/goran_kurucev/EekabYbQD-xNkEjXKZuOsc8BGN2p-_DcwoRbIGEkYte0Gg?e=vdWkwa

_Note: The hand symbol in the link is added automatically and breaks the link. Copy the link in browser and replace hand symbol with : v : (without spaces between them)_

**Comment by papicn** [comment]
In latest develop bug fix is merged, and can be retested

**Comment by goran237** [comment]
This bug has been resolved, and can be closed
