### ISSUE TITLE
Intermittent issue of failing to save the Service and/or Header details (Flow type FILE)

### ISSUE THREAD

**Issue by goran237** [assimbly/gateway#102]
**SUMMARY**
While creating a new flow, some of the combinations of services and headers can be successfully saved, while others cannot (Flow gets saved with some missing details). The issue may not be limited only to combination of certain services and flows. If services are set in some or all the sections, there is no guarantee that all of them will get saved every time.

**STEPS TO REPRODUCE**

Flows Page
Create new flow
Select a combination of service and header for a From section
Fill other mandatory fields in From and To(1) section
Click Apply/Save

**ACTUAL RESULT**
In some of the cases the flow gets saved successfully, in some doesn't. Root cause may be in a particular service or particular header in correspondence to selected Flow type.

**ATTACHMENTS**
https://elanwave-my.sharepoint.com/:v:/p/goran_kurucev/ETHHa9okGKNPgQt1rT0AT5AB27N4jv484YX70h5emBi0Mw?e=ZM2x6N

https://elanwave-my.sharepoint.com/:v:/p/goran_kurucev/EY0ICdcVyqFHjOgFs1ZPk38Byw-hDcDXfoBUJpiCnpEuKg?e=Px4i1c

_Note: The hand symbol in the link is added automatically and breaks the link. Copy the link in browser and replace hand symbol with : v : (without spaces between them)_

**Comment by goran237** [comment]
Validation should take place in terms of which option should be applicable to which flow type. Therefore this bug should remain opened

**Comment by papicn** [comment]
In latest develop bug fix is merged, and can be retested

**Comment by goran237** [comment]
This one has been fixed
