### ISSUE TITLE
Inconsistencies in creating the links for "From" and "To" details in list of flows

### ISSUE THREAD

**Issue by goran237** [assimbly/gateway#107]
**SUMMARY**
After creating a new flow, the links that lead to details of "From" and "To" objects are not always created/displayed in the list of all the flows of a certain gateway

**STEPS TO REPRODUCE**
Flows Page
Create new flow
Select a combination of service and header for a From section
Fill other mandatory fields in From and To(1) section
Click Apply/Save
Navigate to the list of all the flows

**ACTUAL RESULT**
Some of the entries in the list do not have "From" or "To" or both of the links

**ATTACHMENTS**
![image](https://user-images.githubusercontent.com/12623484/41236028-622321f8-6d90-11e8-9cf6-57af480c3822.png)

**Comment by goran237** [comment]
Linked to [https://github.com/assimbly/gateway/issues/109](url)

**Comment by papicn** [comment]
In latest develop bug fix is merged, and can be retested

**Comment by goran237** [comment]
This one has been resolved
