### ISSUE TITLE
Removal of random details from a flow after EDIT->SAVE action (without or with changes to the flow)

### ISSUE THREAD

**Issue by goran237** [assimbly/gateway#109]
**SUMMARY**
When editing the flow (without performing any modifications to the fields) and performing SAVE action, fields From and Error get deleted.

**STEPS TO REPRODUCE**
Flows Page
Open existing flow
Click Edit
Click Save

**ACTUAL RESULT**
On home page, field "From" is missing for the edited flow. Also, inside the flow itself the Error value is missing

**ATTACHMENTS**
https://elanwave-my.sharepoint.com/:v:/p/goran_kurucev/EccSMyoBTrdNkGucW0ncULoB4FGCtCOff2iSNj9L0TfxiQ?e=WTtFcG
_Note: The hand symbol in the link is added automatically and breaks the link. Copy the link in browser and replace hand symbol with : v : (without spaces between them)_

**Comment by goran237** [comment]
This defect is related to [https://github.com/assimbly/gateway/issues/107](url)

**Comment by goran237** [comment]
This issue is not only limited to removal of From and Error details. Services and headers may or may not be saved. Also, at one point the complete To(x) sections were missing.

**Comment by papicn** [comment]
In latest develop bug fix is merged, and can be retested

**Comment by goran237** [comment]
This one has been resolved.
