### ISSUE TITLE
Input Validation for option field

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#11]
Note related: issue 20

**1. User story**

As a user I want to add a valid syntax of options for an endpoint type.

Explanation: Check if the options is a comma separated list. For example the following is valid:

autoCreate=true,bufferSize=28kb

The following is not valid

?autoCreate:true;bufferSize:28kb

Why is the above not valid

- The question mark is added automatically
- Every key value should be separated by =
- every key/value pair should be separated by comma.

**1.1	Acceptance tests**

Check when user edits some false charactoer so that the string create isn't correct.

**1.2	Use case**

Pre-condition:
	- issue 20
Happy flow:
	- Edit key-value pairs
Alternative path:
	No
	
**1.3	Screen information**

Main page (Flow edit page)

**Comment by papicn** [comment]
Task implemented
