### ISSUE TITLE
Intermittent issue of adding sections and swapping To and Error details while editing flow 

### ISSUE THREAD

**Issue by goran237** [assimbly/gateway#111]
**SUMMARY**
When editing the flow, the flow details of "To(1)" and "Error" sometimes get swapped, and values in  "To(2)" and "To(3)" get deleted, with additional field and/or complete section appearing.This is intermittent issue, and happens approximately one in five times

**STEPS TO REPRODUCE**
Flows Page
Open existing multi-endpoint flow
Click Edit

**ACTUAL RESULT**
Details of "To(1)" section are swapped by the ones from "Error" section. Details of other "To" endpoints are deleted and additional ID field appears. Sometimes a complete section appears (see attachment)

ATTACHMENTS
https://elanwave-my.sharepoint.com/:v:/p/goran_kurucev/EY7wugMUoD1KqD11H_c16ToBZBsAV0dBgNSmdSqvZdJ98Q?e=sIcBY0

![image](https://user-images.githubusercontent.com/12623484/41340792-7a592ace-6ef8-11e8-8925-08b4cae07f8e.png)

_Note: The hand symbol in the link is added automatically and breaks the link. Copy the link in browser and replace hand symbol with : v : (without spaces between them)_

**Comment by goran237** [comment]
https://elanwave-my.sharepoint.com/:v:/p/goran_kurucev/ESjBJKpqbpNHsvI6NEoLRNUBqDSm6dWuBPlFj3SRlGC60g?e=JQeghG

Additional info

**Comment by papicn** [comment]
In latest develop bug fix is merged, and can be retested

**Comment by goran237** [comment]
This one has been resolved
