### ISSUE TITLE
Enhancement: Notification to the user when trying to delete a dependent object

### ISSUE THREAD

**Issue by goran237** [assimbly/gateway#119]
When user tries to delete an object that has a dependency to another object, there is no notification on why such an action cannot be performed. It looks like the delete button doesn't perform any action in such cases, which may be confusing.

**Comment by papicn** [comment]
Issue with deleting dependent object is solved

**Comment by goran237** [comment]
Module/Page: Environment Variables
Description: User is able to delete an object that has a dependency to another object
Steps to reproduce: 
1.	Make flow and use existing environment variable
2.	Go to http://localhost:9000/#/environment-variables
3.	Chose environment variable used in flow that is created
4.	Click on delete
5.	Confirm delete operation
6.	Observe that environment variable is delated
Expected result: We should get some kind of notification that environment variable is used in flow and it can’t be deleted

This applies to the service and/or headers that are used in an existing flow

**Comment by goran237** [comment]
This one has been resolved. Per design, deletion of environment variables should be possible even if they are referenced by a workflow
