### ISSUE TITLE
Link to help pages

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#12]
**1. User story**

As a user I can open help to get information about a component so I can see the documentation about for example valid options.

Explanation: Next to endpoint type there should be 2 help buttons. These buttons link to online help pages of the selected componet

First link: There link should link to the Assimbly help for a component as provided by the Wiki.

For example. https://github.com/assimbly/gateway/wiki/components/file

The Assimbly wiki comes with an example and the most common options. The full documentation is available at the second link.	   

A second link directs to the github component page of the Apache camel projects (https://github.com/apache/camel/tree/master/components)

For example: https://github.com/apache/camel/blob/master/camel-core/src/main/docs/file-component.adoc

**1.1	Acceptance tests**

Check when clicking on the link if the component opens. Especially for second link every component should be tested.

**1.2	Use case**

Pre-condition:
	- A flow is created
Happy flow:
	- Click on link and the help page opens in a new tab
Alternative path:
	No
	
**1.3	Screen information**

Main page (Flow edit page)

**Comment by papicn** [comment]
Task implemented
