### ISSUE TITLE
Basic validation for key/values

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#120]
**1. User story**

As user I would to avoid mistakes when editing key/values. Currently there is no validation. When saving a key/value there should be a validation if:

       - The key or value aren't empty (null values aren't allowed)
       - The key name doesn't exist
       - The lenght in the database isn't exceeded (max=255 characters). 

These validation should be aplied on all settings pages that contain key/values: Environment Variables, Services, Headers. If a rule is violated the user should get feedback on this.

**1.1	Acceptance tests**

Create multiple key/values that violates the three base rules (not null, not double and lenght).

**1.2	Use case**

Pre-condition:
	- A gateway is created
Happy flow:
	The user enters the key/values that are valid
Alternative path:
         The user enters the key/values that are invalid.
	
**1.3	Screen information**

Settings (Environment Variables, Services, Headers)

**1.4 Related**

Issue 113 and 114 (bugs/enhancement) are related to this and can also be retested after closing this issue

**Comment by papicn** [comment]
Task implemented
