### ISSUE TITLE
Service keys: add required keys automatically

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#122]
**1. User story**

As user I want that required keys are add automatically when I create a new service. 

Explanation: Currently the user can choose the type of service he want to create. For every type there are some required field. These fields needs to be add after creation. Also could the fields by of a certain type. This should be (hidden) in the created field and later saved to the database. All custom fields are strings.

_JDBC Connection_

url (string)
username (string)
password (password)
driver (list): current list contains only com.mysql.jdbc.Driver

_SonicMQ Connection_

url (string)
username (string)
password (password)

_ActiveMQ Connection_

url (string)

_Kafka Connection_

url (string)

The value field should contain the attributes "datatype=string" and "required=yes".

If required is yes, the user cannot delete this key (if the value has this attribute the delete shouldn't be available).

**1.1	Acceptance tests**

Create a service for example a JDBC connection and check if the required keys are added with the specific fields. For some fields, for example password the value field should show it as password field and when it is a list a combox.

**1.2	Use case**

Pre-condition:
	- A service is created
Happy flow:
	The user create a new service and chooses a service type.
        The keys are shown. 
Alternative path:
         The user changes the service type for an existing service (then all current keys should be optional) and new required fields should be added (if not exist).
         
	
**1.3	Screen information**

Services (Settings)

**Comment by MarijaZembaFE** [comment]
Task implemented.
