### ISSUE TITLE
URI validation

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#123]
**1. User story**

As user I want to be sure that my uri of my endpoints are valid

Explanation: When the user clicks on next or on another endpoint tab the uri (when not empty) can be validated in the backend with rest endpoint on ConnectorResource validateFlow(uri).

The REST endpoint should get the uri in Camel format like this componenttype:uri?options  (just like when hovering the endpoint on the main page).

**1.1	Acceptance tests**

Create a new flow and enters some flows and then click on next then see if it validate. When uri is valid then don't show feedback to the user. When it doesn't work, show the error message to user as a warning (user can still save the flow if he wants).

**1.2	Use case**

Pre-condition:
	- A flow is created
Happy flow:
	The user create a flow with valid uris 
Alternative path:
	The user create a flow with invalid uris (and get a warning)         
	
**1.3	Screen information**

Flow (Edit-all) page

**Comment by papicn** [comment]
Task implemented
