### ISSUE TITLE
Live mode extensions

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#129]
**1. User story**

As user I want that live mode is easier to use and save my work.

Explanation: Currently it's not very clear what the live mode does.

	When the live mode open, add a text to the editor field:

         "Use this editor to configure flows in a text editor. The live mode can be use to try out new flows. A flowsrunning in live mode is not persistent. Then you need to save the flow"

One can create a flow from scratch, use an export of a gateway (Setting --> Gateway --> Export) or use the example button."

        Create a button "Save" which saves the flow into the database.

	Create a button "Add XML example". Then the example from the wiki can be added to the XML editor (https://github.com/assimbly/connector/wiki/XML-Configuration-Example).

        Create a combobox with tree type of files "XML, JSON and YAML" when the flow is set then use one these type to set the flow.

**1.1	Acceptance tests**

         1) Open the live mode and check if the text is set. When user type this message should disappear
         2) Click on button "Add XML Example" to load the XML in text.
         3) Click on "save" button to save to the database

**1.2	Use case**

Pre-condition:
	- no
Happy flow:
	The flow is saved to database 
Alternative path:
	The user gets an error message when flow can not flow (or set)
	
**1.3	Screen information**

Live mode page

**Comment by MarijaZembaFE** [comment]
Task implemented.
