### ISSUE TITLE
Add a new page for maintainance

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#13]
**1. User story**

As user I want to put one or all flows into maintaince mode so these flows are pause during the give time frame.

Explanation: Sometimes flows needs not run for a certain time. For this a new page (under settings) should be created. The name of the page is "maintainance".

The page should have:

        - a hours and minutes field.
        - all list of flows
        - Every box should have check box
        - There should be a button the check all checkboxes
		- There should be a button to apply the configuration
		
I applied the checked flows should go to pause until hours/minutes has been reached.
	   
**1.1	Acceptance tests**

Check if the flows are pause (on main page) if the selected flows on mainaince mode are pause. See maintaince mode is 5 minutes. After 5
minutes the selected flows should resume and work as normal again.

**1.2	Use case**

Pre-condition:
	- two or three flows should be created
Happy flow:
	- Configure maintaince 
		- set time
		- select flows
		- apply change
	- during maintainance mode flows are paused
	- after the set time is over, flows should resume (and work again)
Alternative path:
	No
	
**1.3	Screen information**

Maintainance mode (new)

**Comment by papicn** [comment]
Task implemented
