### ISSUE TITLE
Export XML Configuration

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#14]
*1. User story**

As user I want to export the configuration to a XML File so I can use it later for live or another enviroment

Explanation: Assimbly connector supports XML as configuration. This can be practical if settings needs to imported to another environment. 

At the gateway settings page there should be a new button

- Export button to download an XML Configuration

The button should call the REST API functions

		   
**1.1	Acceptance tests**

Check if click on export button that the XML can be saved to the local filesystem.

**1.2	Use case**

Pre-condition:
	
Happy flow:
	Export --> XML configuration file on filesysteem --> Import --> Configration in database

Alternative path:
	No
	
**1.3	Screen information**

Gateway page (Settings)

**Comment by assimbly** [comment]
See for example for file upload: https://github.com/pqina/filepond

**Comment by papicn** [comment]
Task implemented
