### ISSUE TITLE
Set default endpoint when gateway type is chosen

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#142]
**1. User story**

As user I want that default endpoints are set to ActiveMQ when creating a broker gateway.

Explanation: When the user creates a new gateway, the type of gateway needs to be set. If this is 'broker' then automatically a ActiveMQ server is started. So it is logical that the default endpoints are set to this component type.

**1.1	Acceptance tests**

Create a new gateway. After selecting 'broker' for gateway type, check if the default endpoints (from, to and error) are set to ActiveMQ.

**1.2	Use case**

Pre-condition:
	- No
Happy flow:
	The create a new gateway 
Alternative path:
	The user edit a gateway a changes this from Adapter to Broker. Then also the endpoints should change to "ActiveMQ".        
	
**1.3	Screen information**

Gateway page

**Comment by MarijaZembaFE** [comment]
Task implemented.
