### ISSUE TITLE
Log viewer

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#143]
**1. User story**

As user I want to view the logs of application.

Explanation: Currently the log level can be setting (Administration --> Logs). However to view the log the user needs to go to the web server. A new page should created: Administration --> Log viewer

This page consists of 

Text area (scrollable)
Input field: "Lines:"
                    On hover of this input field the text says: "The number of lines returned (default=250, max=10000). Only the last lines of the log file are shown (tail)."
Button "Refresh"

There is a REST Endpoint for this:

/api/environment/{gatewayid}/log/{lines}

**1.1	Acceptance tests**

Go to the "Log viewer" page. Now the log with the last 250 lines is shown. Change the settings to for example 1000 and click on refresh.

**1.2	Use case**

Pre-condition:
	- None
Happy flow:
	The user see the log
Alternative path:
	If the REST Endpoint doesn't return something error, then in text area the message "Can't get log" should be shown.
	
**1.3	Screen information**

New page:

Log viewer (Administration)

**Comment by papicn** [comment]
Task implemented
