### ISSUE TITLE
Edit a wiretap endpoint like other endpoints

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#144]
**1. User story**

As user I want to edit the wiretap endpoint the same as other endpoints.

Explanation: The wiretap is view and edit on a seperate page. When clicking on edit a popup show the default edit page. What would be better if the same page/fields would be shown as the "from" endpoint as on the edit all page.

**1.1	Acceptance tests**

Go to Settings --> Offloading and create a new wiretap endpoint. 

**1.2	Use case**

Pre-condition:
	- None
Happy flow:
	The user creates a new wiretap endpiont
Alternative path:
        no
	
**1.3	Screen information**

New page:

Offloading (Settings)

**Comment by papicn** [comment]
Task implemented
