### ISSUE TITLE
bug fixes 0.8

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#157]
1) Default endpoints set at gateway page are not taken into account when creating a new flow (for example setting defaults to ActiveMQ)
2) When creating a new service the password field is already filled, though nothing is set yet.

3) Errors on flow status hover
3a) When creating two flows with the same from endpoint (File with samen directory), error is not shown on page.
3b) File to SonicMQ (no SonicMQ is running), error is not shown. Error is returned in response:

<response>
  <action>startFlow</action>
  <details>See the log for a complete stack trace</details>
  <id>1</id>
  <message>unable to start flow 33 failed: Failed to resolve endpoint: sonicmq.133://Sample.Q3 due to: javax.jms.JMSException: java.net.ConnectException: Connection refused: connect: tcp://localhost:2506</message>
  <status>failed</status>
  <statusCode>400</statusCode>
</response>

4) Check before confirm delete if flow is running (status endpoint) (then show cannot delete an active flow)
5) Going from flow to settings pages (for example gateway or environment variables) sometimes notifications in green are shown.
6) Editor mode, not properly feedback when XML is invalid (like in log file)

**Comment by papicn** [comment]
Bugs fixed
