### ISSUE TITLE
"resume" button

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#16]
Note depends on: Issue 2

**1. User story**

As a user I can resume a flow (after pause) so the flows is active again.

Explanation: 

Most buttons like start / restart / stop have been implemented (camel flow entity page). A "resume"button still must be added here, similar to the other buttons. 
(The REST Backend API is already prepared for this).
		   
		   
**1.1	Acceptance tests**

Check when clicking on the start button, the flow can be paused. After pause a click on the resume button should resume the flow. 

**1.2	Use case**

Pre-condition:
	Flow is created 
Happy flow:
	The happy flow is Start --> Pause --> Resume --> Stop 
Alternative path:
	Alternative path is Start --> Pause --> Stop 
		
**1.3	Screen information**

Main page (Flows)

**Comment by papicn** [comment]
Task implemented
