### ISSUE TITLE
Flow buttons

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#17]
Note depends on: Issue 2 and 16

**1. User story**

As a user I only see the buttons on a flow where an action is possible so I don't get confused if I the button can be used. 

Explanation: 

Every flow has the following buttons:

view
edit
delete
start
stop
pause
resume
restart

The idea is to only show the buttons which are relevant to the user. Basicly the following buttons are shown:

 1) Tool button (when hover show actions "view", "edit", "delete". Should not be in color)
 2) Stop button (greyed out when flow not started)
 3) Pause button (greyed out when flow not started) 
 4) Start button
            When started show restarted button
            When paused show resume button

		   
		   
**1.1	Acceptance tests**

Check when clicking on the start button, the "Stop" but should become available. The restart button should change to restart button.

Check when clicking on the pause button, the restart button should change to resume button.

Check when clicking on the stop button, the start button should be at default and stop/pause should be greyed out.

**1.2	Use case**

Pre-condition:
	Flow is created 
Happy flow:
	The happy flow is Start --> Stop 
Alternative path:
	Alternative path is Start --> Pause --> Resume --> Stop 
	
	
**1.3	Screen information**

Main page (Flows)

**Comment by papicn** [comment]
Task implemented
