### ISSUE TITLE
Show status of flow with information about start time

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#18]
**1. User story**

As a user I want to see the latest status of a flow so I can see for each flow if it is started/stopped etc.

Explanation:

The user should see the relevant status of the flow at all time. Herefore can be an extra collumn created (at the end of the flows table). 

Now if a flow starts/stops etc, this is shown on top of the routes table. Instead these messages should be shown in the status field. For example:

                "Started at YYYY-MM-DD HH:MM:SS"
		   
		   
**1.1	Acceptance tests**

Check when clicking on the start button, the user should see "Starting" in the new collum. When OK message get back it should show "started". If then
user clicks on stop it should see "Stopping" and "Stopped" after OK gets backend from the backend. 

**1.2	Use case**

_Pre-condition_
	Flow is created 
_Happy flow_
	Shows messages after receiving OK
		
_Alternative path:_
	If NOK then Error should be shown in the collumn. (When hover it should show the complete error message).

**1.3	Screen information**

Main page (Flows)

**Comment by papicn** [comment]
Task implmented
