### ISSUE TITLE
Live configuration page

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#19]
**1. User story**

As user I want to use live flows so I can configure/manage flows from XML. This is practical for testing and when the database isn't available. 

Explanation: Currently the REST API allows so-called "live configuration". This configuration is not saved to the database, but played 'live'. 
For this at the main page there should be a button with "Live mode". When user clicks on this button the live page opens. This page consists of:

           1) Text area (user can paste a XML configuration). This field should be a XML editor (See http://codemirror.net/). 
           2) Text field "ID"
           3) Load button (set the live configuration)
           4) Start / Stop / Pause / Resume / Restart (Same logic as issue 17)

**1.1	Acceptance tests**

Check when clicking on "live mode" a page opens when live mode. There the following example should be pasted in the text area:

<connector>
	<id>example</id>
	<flows>
		
		 		
		<flow>
			<id>filetofile</id>
			<from>
				<uri>file://C:/Test1</uri>
			</from>
			<to>
				<uri>file://C:/Test2</uri>
			</to>
		</flow>
	</flows>		
</connector>

When user clicks on load button the XML and ID should be sent to the REST URL  http://localhost:8080/api/liveconfiguration

After this the start/stop/pause/resume/resume should work like managing a flow one the main page.

**1.2	Use case**

_Pre-condition_
	No 
_Happy flow_
    After load the xml configuration, when the user starts the flow, the flow should work the same as when starting the same flow from the main page.
		
_Alternative path:_
	No

**1.3	Screen information**

Live page / Main page (Flows)

**Comment by papicn** [comment]
Task implemented
