### ISSUE TITLE
Deployments page

### ISSUE THREAD

**Issue by skin27** [assimbly/gateway#194]
Currently one can only deploy from one Assimbly environment to another by means of import/export. Better would be when this would completly from the GUI. For this a new page under admin must created "Deployments".

For this the maintenance page can be used (copied) as an example and changed to specific functionality. (A mockup will be attached).

**Comment by assimbly** [comment]
![deployments](https://user-images.githubusercontent.com/35961736/50826882-38e56000-133d-11e9-80b0-561f49775779.jpg)

**Comment by assimbly** [comment]
Added mockup.

User story:

As user I want to deploy one or more flows to another environment (another gateway/gateways). I like to select the flows from a list and the click on deploy button (where I can select the environment).

Application logic:

1) User select one or more flows (are all)
2) User clicks on Deploy button (dropdown shows environment) and select on environment name (stage)
        The stage is between parentheses.

        Give a warning message when the stage does not follow the stage of the gateway. No warning if stage
                  Development --> Test
                  Test --> Acceptance
                  Test/Acceptance --> Production

3) For each flow
           a) Call internal API (Export flow):                 

                   get /api/environment/{gatewayid}/flow/{flowid}
    
             Note: This is the same as what the export button does when editing a flow 
           
           b) Call external api:

                   post /api/environment/{gatewayid}/flow/{flowid}   
4. Show result of export (succesful =200 or not on the screen.

Database/Datamodel:

Before the application logic can be implemented first two entities (data tables) needs to be created with JHipster (https://www.jhipster.tech/creating-an-entity/)

Environment

gatewayName 
gatewayId
environmentName:
stage:
url:
apiToken (?)

DEPLOYMENT

flowId
flowName
status
statusMessage
deploymentDate

relationship OneToMany {
	Environment{deployment} to Deployment
}


How to test:

To test this functionality one need two gateway. It's possible to run them on two different ports or on separate machines. One could be configured for example as stage TEST and the other as stage PRODUCTION.

Note that the environment variables value should not be deployed as implemented in #191

**Comment by assimbly** [comment]
This will be used for database extension

**Comment by assimbly** [comment]
Maybe this could also be used for a scheduled backup.

**Comment by assimbly** [comment]
Backup:

- scheduled backup
		- within database and external (Github)
	- backup before deployment

**Comment by assimbly** [comment]
Implemented in 3.0
