### ISSUE TITLE
“pause” button

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#2]
See also issue 16

**1. User story**

As a user I can pause a flow so the flow temporily stops working

Explanation: Most buttons like start / restart / stop have been implemented (camel route entity page). 
A "pause"button still must be added here, similar to the other buttons. (The REST Backend API is already prepared for this).
	
		   
**1.1	Acceptance tests**

Check when clicking on the start button, the flow can be paused. After pause a click the pause button. 

**1.2	Use case**

Pre-condition:
	Flow is created 
Happy flow:
	The happy flow is Start --> Pause Stop 
Alternative path:
	
**1.3	Screen information**

Main page (Flows)

**Comment by papicn** [comment]
Task implemented

**Comment by papicn** [comment]
Task implemented
