### ISSUE TITLE
Options field: Key Value editor

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#20]
**1. User story**

As a user I can edit the options of a flow endpoint (from / to / error) in a key-value editor so I don't need file the options as a string. 

Explanation: Now the options field of an endpoint needs to be entered as follows:

option1=value1,option2=value2

Would like to change this to graphically editing key/value like https://github.com/openshift/angular-key-value-editor. This editor should be shown when user click on option field.	

**1.1	Acceptance tests**

Check when clicking on options add some dummy key-values. For example:

      option1 = value1
      option2 = value2 
   
**1.2	Use case**

_Pre-condition_
	A flow is created
_Happy flow_
        User add key-values and these options are save as option1=value1,option2=value2 to the database
		
_Alternative path:_
	No

**1.3	Screen information**

Page: Main page (Flows Edit page)

**Comment by papicn** [comment]
Task implemented
