### ISSUE TITLE
Show the name of gateway at main page

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#21]
Note: Reletated is issue 4

**1. User story**

As user I want to see the name of gateway at the main page so I can select the gateway to show related flows. 

Explanation: Every gateway has an ID and a name. The database can contain multiple gateways. 
For now the ID field should be hidden and the name field should create and visible to the user at the main page.

		   
**1.1	Acceptance tests**

When open the main page, a combobox should be show with the gateway. Select the other gateway and 
the flows in the table below should be shown. 

**1.2	Use case**

Pre-condition:
	Two gateways should be created in the database (two different names/id). Every gateway should have one or more flows.
Happy flow:
	If the gateway is selected the related flows should be visible.

Alternative path:
	No
	
**1.3	Screen information**

Main page (Flows)

**Comment by papicn** [comment]
Task implemented
