### ISSUE TITLE
Import XML Configuration

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#22]
Related issue 14

*1. User story**

As user I want to import the configuration from a XML File so I can use reuse it from an other enviroment

Explanation: Assimbly connector supports XML as configuration. This can be practical if settings needs to imported to another environment. 

At the gateway settings page there should be a new button

- "Import" button to upload an XML Configuration

The button should call the REST API function: import

		   
**1.1	Acceptance tests**

Check if click on export button that the XML can be saved to the local filesystem (issue 14 should work).
Change one of the configuration in XML (For example the ID)
Check if click on import button that the XML can be selected from filesystem and imported. 

**1.2	Use case**

Pre-condition:
	
Happy flow:
	Import -->
       Select XML configuration file from filesysteem --> 
       Configuration of XML should be seen in database or overwritten

Alternative path:
	No
	
**1.3	Screen information**

Gateway page (Settings)

**Comment by papicn** [comment]
Task implemented
