### ISSUE TITLE
Add live search to combobox

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#23]
**1. User story**

As user I can filter to entries of combobox so I don't have to scroll throug a list

Explanation: Currently most combox fields work with drop down. To following combobox a live search can be added at the flow edit page:

- component combobox
- service combobox
- header combobox

See: https://silviomoreto.github.io/bootstrap-select/examples/#live-search
	   
**1.1	Acceptance tests**

Check if combox works for each combox field with a filter.

**1.2	Use case**

Pre-condition:
	- A flow is created
	- Multiple services are created
	- Mutliple headers are created
Happy flow:
	- Edit flow
	- Select component, service or header
	- Select entry with live filter 
Alternative path:
	No
	
**1.3	Screen information**

Main page (Flow edit page)

**Comment by papicn** [comment]
Task implemented
