### ISSUE TITLE
Create gateway on first startup

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#25]
**1. User story**

User story: As a user I can configure a gateway on first start up.

Explanation: If the user starts the gateway for the first time, the gateway node doesn't have gateway configured yet. Before flows can configured, first a gateway must be created.

This why on first startup (no gateway node created). (Backend checks for this will be implementated later). Not the flow page should shown, but a

text: No gateway have been configured for this node. Please create one first.
button: "Create gateway"

If user clicks on buttons it is redirected (routed) to --> Settings --> Gateway page

**1.1	Acceptance tests**

Empty the gateway table in the database. When users login and gateway variable is empty, show gateway page

**1.2	Use case**

Pre-condition:
	- No gateway has been configured yet
Happy flow:
	- Page to create gateway is shown and if he clicks to user goes to theGateway page
Alternative path:
	- No
	
**1.3	Screen information**

Main page (After login)

**Comment by papicn** [comment]
Task implemented
