### ISSUE TITLE
Hover on endpoint shows tooltip with information about the endpoint

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#3]
**1. User story**

As a user I can see extra information about a flow when I move my mouse on top of it so I don't have to go the view or edit page.

Explanation: Currently you only see the name and component type of every flow (FILE, JDBC, SFTP etc). Also the URI and options should be shown in a tooltip as soon as the user hovers with his mouse is on a from or to endpoint type. Perhaps not directly, but after more than x ms. It should be shown in the Camel way like follows:

component://uri?options

for example

file://directoryName[?options] 

		   
**1.1	Acceptance tests**

Check when hover on a from or to component to see example as below. 

**1.2	Use case**

Pre-condition:
	A flow is created 
Happy flow:
	Hover on flow and see information
Alternative path:
	The path differs on component. See http://camel.apache.org/components.html for the correct URI syntax.
**1.3	Screen information**

Main page (Flows)

**Comment by papicn** [comment]
Task implemented
