### ISSUE TITLE
Gatway name or environment should be used in title screen

### ISSUE THREAD

**Issue by mvweerd** [assimbly/gateway#374]
When using multiple environments it is not clear on which environment you are configuring (only in addressbar)

Maybe the environment name can be used in stead of the fixed "Gateway" text in the GUI
![image](https://user-images.githubusercontent.com/4272279/83524117-6c50fd80-a4e3-11ea-9ac1-ab73bc48418f.png)

**Comment by assimbly** [comment]
Will be added to first alpha.
