### ISSUE TITLE
Multiple outgoing endpoints causes reply to disappear

### ISSUE THREAD

**Issue by mvweerd** [assimbly/gateway#384]
When a flow is configured with 1 incoming JETTY endpoint and 2 outgoing endpoints (1 http + 1 file) the http response is not routed back to the incoming Jetty endpoint.

**Comment by mvweerd** [comment]
`<flow>
            <id>1</id>
            <name>test-123-flow</name>
            <autostart>false</autostart>
            <offloading>true</offloading>
            <maximumRedeliveries>0</maximumRedeliveries>
            <redeliveryDelay>3000</redeliveryDelay>
            <logLevel>INFO</logLevel>
            <from>
               <id>1</id>
               <uri>jetty:http://0.0.0.0:8026/test-123-flow</uri>
               <options>
                  <matchOnUriPrefix>true</matchOnUriPrefix>
                  <exchangePattern>InOut</exchangePattern>
               </options>
            </from>
            <to>
               <id>1</id>
               <uri>http:localhost:8024/test-123-flow</uri>
               <options>
                  <bridgeEndpoint>true</bridgeEndpoint>
                  <throwExceptionOnFailure>false</throwExceptionOnFailure>
               </options>
            </to>
            <to>
               <id>67</id>
               <uri>file://E:\Assimbly\data\test-123-flow</uri>
               <options>
                  <allowNullBody>true</allowNullBody>
               </options>
            </to>
            <error>
               <id>1</id>
               <uri>file://E:\Assimbly\data\err</uri>
            </error>
         </flow>`

**Comment by assimbly** [comment]
The reason it doesn't work is that Assimbly uses parallel processing (this turns request/reply off) with multiple to endpoints. For now on (3.4.0 Beta 2) you set the from header ParallelProcessing=false. Then it works. In later version this will be a flow setting.
