### ISSUE TITLE
Show the name of gateway at edit flow page

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#4]
**1. User story**

As user I want to see the name of gateway when editing a flow so I can select the gateway based on name instead of ID.

Explanation: Every gateway has an ID and a name. The database can contain multiple gateways. 
For now the ID field should be hidden and the name field should create and visible to the user.

		   
**1.1	Acceptance tests**

Check when creating a new flow that the gateway can be selected by name. 

**1.2	Use case**

Pre-condition:
	A flow is created 
Happy flow:
	If the gateway is selected it should be save by ID to the database in the flow table

Alternative path:
	No
	
**1.3	Screen information**

Main page (Flows edit page)

**Comment by papicn** [comment]
Task implemented
