### ISSUE TITLE
Showing gateway or not

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#40]
**1. User story**

Assimbly can be used as standalone version (with only one gateway) or as distributed version (multiple gateways). As a user I only want to select a gateway when there are more than one gateway available.

On the main page (flows) the logic must be as follows:

   - If there are no gateway show button to create gateway (already implemented)
  - If there is one gateway  show text: Showing flows for gateway {gatewayname}
  - If there is more than one gateway show: Showing flow for gateway {combobox with gateway name}

On the main page (flows edit-all) the logic must be as follows:

  - If there is one gateway  hide the gateway fields
  - If there is more than one gateway show: Show gateway {combobox with gateway name}
		   
**1.1	Acceptance tests**

Create one gateway and check if the user doesn't see the select gateway options anymore. If there are two created (in the database) the comboboxes should be shown.

**1.2	Use case**

Pre-condition:
	- An gateway should be created first 
Alternative path:
	Two gateways
	
**1.3	Screen information**

Main page (Flows) and Flow edit page)

**Comment by papicn** [comment]
Task implemented
