### ISSUE TITLE
Special characters in values not working from flow properties

### ISSUE THREAD

**Issue by mvweerd** [assimbly/gateway#402]
When a '=' character  is in a sftp password, the flow is not working. all characters after the '=' are not taken  into account.
When the value is filled from a environment variable you can work-around this issue

**Comment by assimbly** [comment]
The reason that '=' character doesn't work is because a Camel uri uses this sign for its parameter for example:

file://C:\test?autoCreate=true&directoryMustExist=true

Assimbly splitted this on the '=' character. Now it only looks at the first = sign.

**Comment by assimbly** [comment]
Fixed in 3.1.0 beta1
