### ISSUE TITLE
logfiles are written twice (also in user_home\.assimbly\logs)

### ISSUE THREAD

**Issue by mvweerd** [assimbly/gateway#404]
in the assimbly log directory is a logfile "gateway_20201112.out.log" 
an almost identical logfile is found in  user_home\.assimbly\logs with the name "2020-11-12.assimbly.log"

**Comment by assimbly** [comment]
- log is by default to "user_home.assimbly\logs with the name "2020-11-12.assimbly.log"
- Other log is because of configuration in Windows Service

**Comment by assimbly** [comment]
Needed is:

- How to configure log directory with startup parameters (Documentation)
- Is it possible to only write to stdout and not to log file

**Comment by assimbly** [comment]
What happens is the following:

By default Assimbly write all log lines to "CONSOLE" and "FILE". The Windows Service is configured to write the CONSOLE logs to a file. Now two files are created. What can be done is:

1) Uncomment writing logs in de Windows Service configuration and change the log location
 
Or

2) Create a custom logback.xml and remove written the log the file. 

More information on the Wiki

https://github.com/assimbly/gateway/wiki/Logging
