### ISSUE TITLE
Combination of options makes flow corrupt

### ISSUE THREAD

**Issue by mvweerd** [assimbly/gateway#405]
Reproduceable with set of options:

![2020-11-18 10_56_36-Greenshot beeldbewerker](https://user-images.githubusercontent.com/4272279/99515126-d7589880-298c-11eb-9cfb-67acbfa6fc15.png)

After saving a short error is shown and after that the flow cannot be opened anymore

**Comment by mvweerd** [comment]
Had to be fast to collect error on screen:
![Uploading ERROR.png…]()

**Comment by assimbly** [comment]
Solved beta 1
