### ISSUE TITLE
Show feedback on errors when saving flow

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#41]
**1. User story**

When saving a flow (edit-all) the user clicks on the save button. This save button is then temporaly unavaible. If saving is finished it is available again. When saving goes wrong (for example the gatewayid is not correct) it should be clear that flow is not saved.
		   
**1.1	Acceptance tests**

Save a flow with a gatewayid that doesn't exist and return "Saving failed (check logs)" to the screen.

**1.2	Use case**

Pre-condition:
	- A gateway should be created
Happy flow:
	The happy flow is just saving (everything is saved properly). This issue is about when something goes wrong and give that feedback to the user
Alternative path:
	Show error message
	
**1.3	Screen information**

Main page (Flow edit page)

**Comment by papicn** [comment]
Task implemented
