### ISSUE TITLE
Flow options multiple TO endpoints are mixed when importing configuration

### ISSUE THREAD

**Issue by mvweerd** [assimbly/gateway#441]
When importing a configuration of  a assimbly gateway and a flow has multiple endpoints, the options of the TO endpoints are merged to both endpoints.

In the exported XML the endpoints-options are correctly specified

example XML below
When this xml is imported the two TO endpoints contain both copyAndDeleteOnRenameFail  AND autoCreate option
`<flow>
            <id>65</id>
            <name>testflowMultipleEndpoints</name>
            <autostart>false</autostart>
            <offloading>false</offloading>
            <maximumRedeliveries>0</maximumRedeliveries>
            <redeliveryDelay>3000</redeliveryDelay>
            <logLevel>OFF</logLevel>
            <from>
               <id>65</id>
               <uri>file://c:\temp\test</uri>
               <options>
                  <allowNullBody>true</allowNullBody>
               </options>
            </from>
            <to>
               <id>65</id>
               <uri>file://c:\temp3</uri>
               <options>
                  <copyAndDeleteOnRenameFail>true</copyAndDeleteOnRenameFail>
               </options>
            </to>
            <to>
               <id>66</id>
               <uri>file://e:\temp</uri>
               <options>
                  <autoCreate>true</autoCreate>
               </options>
            </to>
            <error>
               <id>65</id>
               <uri>file://c:\error</uri>
            </error>
 </flow>`

**Comment by assimbly** [comment]
Part of 3.3.0 Beta1
