### ISSUE TITLE
[3.1.0] Cannot run on client, required JRE 11

### ISSUE THREAD

**Issue by smackdun** [assimbly/gateway#442]
Dear all,

I cannot run new version 3.1.0 on client because it required JRE 11. But i cannot find JRE 11 to download, even i tried installing JDK 11 but not working. 

Please help.

Thank you all very much,

**Comment by assimbly** [comment]
Can you provide more info on the OS you are?

I recommend installing OpenJDK: https://adoptopenjdk.net/

Verify that your Java home is properly: java -version  (or start Java11 directly from its bin directory)
If the JDK is still an issue, I would recommend 3.0 for now (still working on some fixes for new designed edit of flows in 3.2).

Note: If you are on Windows and you like to try JDK11 without administration rights you can try scoop:

Open a Powershell:

Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')

scoop bucket add java
scoop install adopt11-hotspot

Java 11 is then installed in the following directory: "C:\users\{username}\scoop\applications and your java_home is automatically set.

**Comment by smackdun** [comment]
> Can you provide more info on the OS you are?
> 
> I recommend installing OpenJDK: https://adoptopenjdk.net/
> 
> Verify that your Java home is properly: java -version (or start Java11 directly from its bin directory)
> If the JDK is still an issue, I would recommend 3.0 for now (still working on some fixes for new designed edit of flows in 3.2).
> 
> Note: If you are on Windows and you like to try JDK11 without administration rights you can try scoop:
> 
> Open a Powershell:
> 
> Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
> 
> scoop bucket add java
> scoop install adopt11-hotspot
> 
> Java 11 is then installed in the following directory: "C:\users{username}\scoop\applications and your java_home is automatically set.

Dear,

Sorry for the missing information: my OS is Windows Server 2016

I tried to install OpenSDK from your link but still not OK.

I think i will be back to version 3.0.0 for now and come back later.

Thank you very much for your quick support.

Best regards,

**Comment by assimbly** [comment]
Hi thanks for the extra information. Assimbly has been tested on Windows Server 2016, so it should work. I just released 3.2.0. You may download them and start in a Powershell.

1) Open a powershell
2) java -version
3) java -jar gateway{version}.jar

Note: it may be good to rename the ".assimbly" folder in (C:/users/{myusername}/.assimbly to .assimbly.old. In this way it starts fresh.

Please attach the powershell logging to this ticket.

**Comment by smackdun** [comment]
Thank you for your reply,

I downloaded the new version 3.2.0 and can can start the service now.

*** the problem is in my script to install Assimbly as a Windows Services>> solution: in the script, I directly excecuted java ver11 and it's all good.

Best regards,

**Comment by assimbly** [comment]
OK, great. I updated the user guide to include the path to the Java executable for a Windows Service.

https://github.com/assimbly/gateway/wiki/user-guide
