### ISSUE TITLE
Jetty http endpoint is not working from version 3.1.0 and higher

### ISSUE THREAD

**Issue by mvweerd** [assimbly/gateway#487]
When creating a flow with a FROM Jetty endpoint, the flows starts, gets green but does not accept messages. Postman gives an error:

![image](https://user-images.githubusercontent.com/4272279/112324059-a7126500-8cb2-11eb-8e9f-a51ccb6a5faa.png)

**Comment by assimbly** [comment]
The error:

Error: Parse Error: Expected HTTP/

Comes from that HTTPS is expected. This is because it was set globally. Now I don't set it globally, but by endpoint.

Fixed in beta2
