### ISSUE TITLE
Add statistics to popover flow status

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#49]
1. User story

Currently the popover for flowStatus only shows when a flow is started. There is now a new REST endpoint (flow/stats) that gives more information. As a user I would like to present those stats in a human readable way.

The stats endpoint gives the following JSON:

{
  "stats": {
    "deltaProcessingTime": -7,
    "exchangesCompleted": 3,
    "exchangesFailed": 0,
    "externalRedeliveries": 0,
    "failuresHandled": 0,
    "firstExchangeCompletedExchangeId": "ID-win81-1525374066313-0-1",
    "firstExchangeCompletedTimestamp": "2018-05-03T21:04:39.275+0200",
    "firstExchangeFailureExchangeId": "",
    "firstExchangeFailureTimestamp": "1970-01-01T00:59:59.999+0100",
    "lastExchangeCompletedExchangeId": "ID-win81-1525374066313-0-9",
    "lastExchangeCompletedTimestamp": "2018-05-03T21:04:39.317+0200",
    "lastExchangeFailureExchangeId": "",
    "lastExchangeFailureTimestamp": "1970-01-01T00:59:59.999+0100",
    "lastProcessingTime": 10,
    "maxProcessingTime": 40,
    "meanProcessingTime": 22,
    "minProcessingTime": 10,
    "redeliveries": 0,
    "resetTimestamp": "2018-05-03T21:04:23.048+0200",
    "startTimestamp": "2018-05-03T21:04:23.048+0200",
    "totalProcessingTime": 67
  }
}

In the popover I would like to see (in comment the source field in JSON):

Start time: 2018-05-03 21:04:23 (startTimestamp)
Running: 2 hours 1 minute (Now() - startTimestamp)

Processing time:

Last: 10 ms   (lastProcessingTime)
Min: 22: ms (minProcessingTime)
Max: 40 ms (maxProcessingTime)
Avarage: 22 ms (meanProcessingTime)     

Completed:

Number of messages: 10 (exchangesCompleted)
First: 2018-05-03 21:04:23 (firstExchangeCompletedTimestamp)
Last: 2018-05-03 21:04:23 (lastExchangeCompletedTimestamp)

Failures

Number of messages: 10 (exchangesFailure)
First: 2018-05-03 21:04:23 (firstExchangeFailureTimestamp)
Last: 2018-05-03 21:04:23 (lastExchangeFailureTimestamp)

If no information is available for a stat show at number of messages "0" and for timestamps "-"

1.1 Acceptance tests

Start a flow (file to file) and check the results of the popover after:

0 send
1 send
5 send

1.2 Use case

Pre-condition:
- A flow should be created
Happy flow:
The happy flow is when a user puts a mouse on the flow status and the popover shows the stats
Alternative path:
Show: No information (if the flow is at Stopped state)

1.3 Screen information

Main page

**Comment by papicn** [comment]
Task implemented
