### ISSUE TITLE
"Apply" and "Save" button

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#5]
**1. User story**

As a user I want to save or apply the change so I can choose to stay on edit page (apply) or return back to overview page (save).

Explanation: For each configuration page (both main page and the settings pages) the save button must be renamed to apply. In addition, an extra Save button can be add.

The apply button only saves the changes
The save button save the changes and then go back to the overview page.

		   
**1.1	Acceptance tests**

Check every edit page, but editing a configuration and the
 
         - If apply button is clicked that it is saved, but user stay on page
		 - If save button is clicked that it is save, but user goes back to overview page (of what is edited)

**1.2	Use case**

Pre-condition:
	- No 
Happy flow:
	After click changes should be saved. If "apply" is clicked, the user stays on page if "save" button is clicked, user goes back to settings page

Alternative path:
	No
	
**1.3	Screen information**

Main page (Flow edit page) and Settings pages (Edit pages)

**Comment by papicn** [comment]
Task implemented
