### ISSUE TITLE
Restyle gateway page

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#50]
**1. User story**

Currently the gateway page is very simple. As a user the page should have the same look-and-feel as the flow view/edit page. The page can be restyled to look better

**1.1	Acceptance tests**

Check if all data is shown on the page.

**1.2	Use case**

Pre-condition:
	- a gateway is created
Happy flow:
	- Settings --> gateway
Alternative path:
	No
	
**1.3	Screen information**

Gateway page (Settings)

**Comment by MarijaZembaFE** [comment]
Task implemented.
