### ISSUE TITLE
Show names, instead of id while edit from/to/error endpoints directly

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#51]
**1. User story**

As a user I would like to select headers/services by name instead of id.

Explanation: When users are editing a flow they can select the header/service by name, but when the click on the endpoint from the main page they see only the id's.

**1.1	Acceptance tests**

Open the main page and then click on a from or to endpoint. Then you see the 'view' page of the endpoint. There the names should be visible. Also when clicking on edit, the names should be visible (and the id's hidden). When saving the endpoints the id's should be visible. 

**1.2	Use case**

Pre-condition:
	- a flow is created
        - a service is created
        - a header is created
Happy flow:
	- Click on from or to endpoint
	- Click Edit
        - Select/Change service and headers by name
	- Save flow
        - Repeat above steps and change should be visible 
Alternative path:
	If save fails (http error 400) the user should be notified (See issue 41)
	
**1.3	Screen information**

from-endpoint / to-endpoint / error-endpoint

note that error-endpoint page cannot be reached by a link. The link should be entered in the browser address directly like this: http://localhost:9000/#/error-endpoint/{id}

**Comment by papicn** [comment]
Task implemented
