### ISSUE TITLE
Set autostart to false by default

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#52]
**1. User story**

As user now I have to select for each flow if the flow needs autostart or not. Therere should be default. 

**1.1	Acceptance tests**

When create a new flow the field should be set to false.

**1.2	Use case**

Pre-condition:
	- none
Happy flow:
	- Create new flow
Alternative path:
	No
	
**1.3	Screen information**

Main page (Flow edit page)

**Comment by papicn** [comment]
Task implemented
