### ISSUE TITLE
Set header/service to new when nothing is selected

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#53]
**1. User story**

As a user I would like to create a new service or header when editing a flow, when nothing is selected.

Explanation: now there is only an edit button to link to a specific header or service (to edit it), but when nothing is selected this makes no sense, in that case the button should show "New service" or "New header"

**1.1	Acceptance tests**

Check when the service (or header) field is empty that button shows "New service". After clicking on the link the new service should be created. After creation the user should return back to the page and the service is selected. The button should say "Edit service"

**1.2	Use case**

Pre-condition:
	- none
Happy flow:
	- Edit flow 
	- Click on "New service"
	- Save service
        - Return to "Edit flow"
Alternative path:
	Same counts for header
	
**1.3	Screen information**

Main page (Flow edit page)

**Comment by papicn** [comment]
Task implemented
