### ISSUE TITLE
Don't show gateway field when editing environment variables

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#54]
**1. User story**

As a user I don't need to select gateway when editing a gateway.

Explanation: When only one gateway is created it makes no sense to select when when creating an environment variable.

**1.1	Acceptance tests**

Create new environment variable. The gateway selection should be hidden. When saved the gateway id should be added to the database.

**1.2	Use case**

Pre-condition:
	- a gateway is created
Happy flow:
	- Create new environment variable 
Alternative path:
	No
	
**1.3	Screen information**

Environment (Create/Edit page of environment variables)

**Comment by MarijaZembaFE** [comment]
Task implemented.
