### ISSUE TITLE
3.5.0 beta bugfixes

### ISSUE THREAD

**Issue by ghost** [assimbly/gateway#573]
+ Key Value labels at send 
	+ Headers
	+ JMS Headers
+ Show error when something goes wrong when sending a message 
+ Running broker pas na check op false zetten?
+ First row in message viewer stays empty
+ Make broker red when address already in use
+ If classic show classic documentation, if artemis show artemis documentation
+ Delete unused code (sender)
+ Log broker "State" on stop/start/restart
+ Timestamp of Artemis messages to human readable format

**Comment by assimbly** [comment]
Part of 3.5.0 beta5
