### ISSUE TITLE
Having SonicMQ as an error endpoint results in a flow failing to start

### ISSUE THREAD

**Issue by mvweerd** [assimbly/gateway#574]
Having SonicMQ as an error endpoint results in a flow failing to start. 

The error it gives: No endpoint could be found for sonicmq://..... please check your classpath the neede Camel component jar

**Comment by assimbly** [comment]
Sonic endpoints are loaded for each endpoint separately as custom SJMS endpoint. This wasn't done properly for the error endpoint. Solved in 3.5.0 Beta9
