### ISSUE TITLE
Support make tutorial for call API by schedule

### ISSUE THREAD

**Issue by duonglx** [assimbly/gateway#576]
Dear Bro,

I like this project.

I hope you can make more tutorials for us. I tried to make configuration flow call rest API and write to file or database, but I got an error... 

Could you please make a sample or tutorial like this?
https://dzone.com/articles/calling-rest-api-from-camel-route

Thank you in advance~

**Comment by assimbly** [comment]
You can check the latest tutorial to do this: https://github.com/assimbly/gateway/wiki/tutorial-scheduled-rest-call

Two notes. You need the latest release (3.5.0) to use the scheduler. The tutorial is done with the scheduler and REST component. A similar result could be done with the timer and HTTP component.

**Comment by duonglx** [comment]
Great,

I really appreciate your enthusiasm. 
Thank you very much.
