### ISSUE TITLE
"Clone" button

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#6]
**1. User story**

As user I can clone an existing configuration so I don't have to create new entry from scratch for a similar configuration.

Explanation: Often a user creates a similar flow or service. Maybe only one field changes. To make this faster the edit page of an existing flow/service etc should get a clone button. 
When using the clone button all fields should stay the same but the ID should be deleted. When saving the cloned configuration there should be created as a new item. 

		   
**1.1	Acceptance tests**

Take an existing flow, service etc. Click on the clone button. Change one of the field and save this configuration. 
The new configuration should be edited to the list in the overview of the configured item

**1.2	Use case**

Pre-condition:
	- An item should be created first 
Happy flow:
	An existing configuration item can cloned, edited and then saved with a new ID.
Alternative path:
	No
	
**1.3	Screen information**

Main page (Flow edit page) and Settings pages (Edit pages)

**Comment by papicn** [comment]
Task implemented
