### ISSUE TITLE
Bugs for milestone 0.3

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#63]
List of small fixes/adjustments:

1) Gateway on mainpage 

"Showing flow for gateway Test" should be "Showing flows for gateway Test" (flows instead of flow)
Make the gateway name on the main page "Italic"

2) Make buttons in flows/edit-all the same size: 

	question mark / camel
	+x
	New service/Edit service
	New header /Edit header 

3) Make question mark button "blue", instead of grey.
4) Cancel Flow Edit-all --> should go back to "Flows" page (Now it goes back to view page)
6) Double entry when editing an endpoint directly (from flows main page)
7) Can't save endpoint (services/headers)  when editing an endpoint directly (from flows main page)
8) Options editor: If there are (for example three options) and the user use plus. One new entry is created below the plus button and one at the bottom.
9) Please link following component to:

activemq --> https://github.com/apache/camel/blob/master/components/camel-jms/src/main/docs/jms-component.adoc
sonicmq  --> https://github.com/apache/camel/blob/master/components/camel-sjms/src/main/docs/sjms-component.adoc
wastebin --> https://github.com/apache/camel/blob/master/camel-core/src/main/docs/mock-component.adoc

10) Wiki links. Now the wiki links link all to:

https://github.com/assimbly/gateway/wiki/components

This should be:

https://github.com/assimbly/gateway/wiki/Name-Component

Proably this is already solved with issue 64

11) Edit-all

When a user saves a flow, the user only gets feedback when there is an error. Better would be to give also feedback when the save is successful

12) Statistics

- Title should be "Stats", in stead of Status
- Running says "minute" even though minutes are bigger than 1
- It should be "Processing", instead of "Processing:" and "Completed", instead of Completed:" 
- If the date is 1970-01-01 00:59:59 (It's enough to check if date starts with 1970) then show in the popup "-" (This is for "First:" and "Last:" at Completes and Failures.

13) 

Now the stats are showing on hover of the flow status. It would be better to create a separate icon for this (Like the ones https://www.google.nl/search?q=stats+icon&safe=off&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwiy_v2bpY_bAhWHzqQKHVBlCIEQsAQIKA&biw=1536&bih=750). The stats are showing on hover.

14) When stats is stopped, still shows running stats. The REST API now returns 0 when a flow is stopped.

15) Flows/Edit-All

Remove "ToEndpoint" should be "To endpoint"

16) Questionmark (?) on hover of an endpoint on main page, even though there are no options.

17) After a certain time user needs to relogin (revalidation), but then it doesn't show the flows.

18) http://localhost:8080/#/gateway/33 doesn't show all 'gateway' fields of the gateway page

**Comment by MarijaZembaFE** [comment]
Task implemented.
