### ISSUE TITLE
Make the documentation links configurable

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#64]
**1. User story**

As user I would like to change the base link to configuration from the application.yml.

Explanation: Currently the link is hardcoded in the front-end of the application. Wish is to create variables for this for the link to the Assimbly Wiki and to Camel documentation. This link should be place in application.yml (In the directory: /src/main/resources/config) like this:

application:
	documention:
		url: https://github.com/assimbly/gateway/wiki		
		camelurl: https://github.com/apache/camel/blob/master

 		   
**1.1	Acceptance tests**

Create variables from the links in the application.yml and test this with the File component if the links still work to the Wiki and Camel documentation

**1.2	Use case**

Pre-condition:
	- No (Create a flow) 
Happy flow:
	The button should link to the correct documenation page
Alternative path:
	No
	
**1.3	Screen information**

Main page (Flow edit page)

**Comment by papicn** [comment]
Task implemented
