### ISSUE TITLE
REST API: ToEndpoints

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#65]
**1. User story**

As user (developer) I like to save or update multiple endpoints at once.

Explanation: Currently the REST API can only save or update one endpoint at the time. Because a flow can have multiple endpoints a second endpoint can be created to save or update it from an array/list.
		   
**1.1	Acceptance tests**

Acceptance can be from Swagger (Administration --> API)

Save from API (/to-endpoints):

 1a) Save one endpoint
1b) Update one endpint

 2a) Save three endpoints
 3a) Update three endpoints

**1.2	Use case**

Pre-condition:
	Create a flow
Happy flow:
          Create flow with one endpoint, add another one and update it
Alternative path:
	Create a flow with multiple endpoints at once
	
**1.3	Screen information**

No screens

**Comment by papicn** [comment]
Task implemented
