### ISSUE TITLE
Create/Edit header and headerkeys in one page

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#66]
**1. User story**

As user I would like to create/edit a header and headerkeys in one screen.

Explanation: Now a user needs firstly create a header and then the header keys (selecting the header ID). The create/edit pages for header and headerkeys should be merged into one page. 

Of course the header page should be first saved/updated and when the id is returned the headerkeys based on the id of the header (just like saving a flow). 

For editing the headerkeys there could be table like adding options for flow. There are only three fields. The "type" for headerskeys can a combobox with two options: "constant" or "xpath" where constant should be the default.

**1.1	Acceptance tests**

Go to settings and headers
Create a new header
Then the header as well as the keys are created in the database

**1.2	Use case**

Pre-condition:
	- A gateway is created
Happy flow:
	Go to headers page and create a header
Alternative path:
	If there headers can't be save an error should be shown.
	
**1.3	Screen information**

Headers (Settings pages)

**Comment by MarijaZembaFE** [comment]
Task implemented.
