### ISSUE TITLE
Restyle Headers page

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#67]
**1. User story**

As user I like to easily view headers (Settings-->headers) 

Explanation: The headers page consists of two objects:

    Header
    HeaderKeys
	
The page should load both objects in the header page. The header page can be restyled so that 

1) The title: Headers is shown as we the button "Create new header" 
2) Name: (With a dropdown like the type at endpoints)	 showing the header name
3) Table with key / value / type (directly under the name). The title "headers key" can be left out, as well as "create new header keys" button.

The first point is already there so shouldn't be change, the second and third point should be restyled. Only the headerkeys should be shown for the specific selected ID.
		   
**1.1	Acceptance tests**

Go to settings and headers. One header with keys should be shown. If the user select another header the correct keys should be shown in the table.

**1.2	Use case**

Pre-condition:
	- A gateway is created
Happy flow:
	Go to headers page and select header to show keys
Alternative path:
	No
	
**1.3	Screen information**

Headers (Settings pages)

**Comment by MarijaZembaFE** [comment]
Task implemented.
