### ISSUE TITLE
Create/Edit service and servicekeys in one page

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#68]
**1. User story**

As user I would like to create/edit a service and servicekeys in one screen.

Explanation: Now a user needs firstly create a service and then the service keys (selecting the service ID). The create/edit pages for service and servicekeys should be merged into one page. 

Of course the service page should be first saved/updated and when the id is returned the servicekeys based on the id of the service (just like saving a flow). 

 - For editing the servicekeys there could be table like adding options for flow.

**1.1	Acceptance tests**

Go to settings and services
Create a new service
Then the service as well as the keys are created in the database

**1.2	Use case**

Pre-condition:
	- A gateway is created
Happy flow:
	Go to services page and create a service
Alternative path:
	If there services can't be save an error should be shown.
	
**1.3	Screen information**

services (Settings pages)

**Comment by MarijaZembaFE** [comment]
Task implemented.
