### ISSUE TITLE
Restyle Services page

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#69]
**1. User story**

As user I like to easily view all services (Page: Settings-->services) 

Explanation: The services page consists of two objects:

    service
    serviceKeys
	
The page should load both objects in the service page. The service page can be restyled so that 

1) The title "Services" is shown as the button "Create new service" 
2) Name: (With a dropdown like the type field at endpoints)	 showing the service name
3) Type: This can also a dropdown like the type field at endpoints*.  
4) Table with key / value (directly under the name). The title "services key" can be left out, as well as "create new service keys" button.

The first point is already there so shouldn't be change, the second and third point should be restyled. Only the servicekeys should be shown for the specific selected ID.
		   
*Valid entries are "JDBC Connection","SonicMQ Connection", "ActiveMQ Connection" and "Kafka Connection"

**1.1	Acceptance tests**

Go to settings and services. One service with keys should be shown. If the user select another service the correct keys/values should be shown in the table below the selected service.

**1.2	Use case**

Pre-condition:
	- A gateway is created
       - A Service with serviceskeys is created
Happy flow:
	Go to services page and select a service to show servicekeys
Alternative path:
	No
	
**1.3	Screen information**

Services (Settings pages)

**Comment by MarijaZembaFE** [comment]
Task implemented
