### ISSUE TITLE
Assimbly Connector: when cloning a service, the optional service keys of the original service are lost

### ISSUE THREAD

**Issue by petervdz** [assimbly/gateway#690]

**Comment by assimbly** [comment]
What version did you use for this 3.6.0. Because I had this problem as well, working now on 3.7.0 Beta (it should be solved in that version, hope to release that version later this summer).

**Comment by petervdz** [comment]
Hi Raymond, thanks a lot - we are running on version 3.5.0. So when 3.7.0 is released we can plan an upgrade later this year.

**Comment by skin27** [comment]
Closing as Thomas port this to Fuse.
