### ISSUE TITLE
IBM MQ: Connecting to multiple IBM Queue managers doesn't work

### ISSUE THREAD

**Issue by petervdz** [assimbly/gateway#693]
When connecting via IBM MQ queues, it is not possible to connect via multiple services which connect via different IBM MQ queue managers. Only the last activated flow (and other flows that use the same queue manager) works, the other flows get IBM MQ errors as JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2085' ('MQRC_UNKNOWN_OBJECT_NAME'). @tomosjut or  Eelco Winter can maybe explain better, something to do with cashing the right settings per service / queue manager on the assimbly connector.

**Comment by assimbly** [comment]
I will discuss this with @tomosjut. 

Note you can workaround this, by spinning up a second instance on a different port.

**Comment by skin27** [comment]
Closing as Thomas port this to Fuse.
