### ISSUE TITLE
Show name of service of header instead of id

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#7]
**1. User story**

As user I can select a service of header by name (instead of id).

Explanation: Currently only the ID of service and header is shown. This field should be hidden, 
instead a new field should be added where the user can select the service or header configuration by name. The ID should be automatically filled in on the background.
	   
**1.1	Acceptance tests**

Check if

**1.2	Use case**

Pre-condition:
	- A flow is created
	- A service is created
	- A header is created
Happy flow:
	- Edit flow
	- Select service or header by name
	- Save flow 
Alternative path:
	No
	
**1.3	Screen information**

Main page (Flow edit page)

**Comment by papicn** [comment]
Task implemented
