### ISSUE TITLE
Show status of flow

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#73]
**1. User story**

As user I would like to see the status on a flow.

Explanation: Currently when hovering on flow status, you see the flow stats. In issue 63 this is moved to a stats icon. Now when hover on the flow, one should see the status of the flow. Which means show the current status and latest error.

Instead of the current text (which shows the last action), a button should be created

If last action was start/restarted/resumed then make the button green with text "active"
Else if last action was pause makes the button yellow with text "paused"
Else if last action was stopped makes the button blue with text black "inactive" 
Else when error makes the button red with text "inactive"

* One should try what works/looks best for this button. I could look like:

https://torbjornzetterlund.com/passing-data-list-bootstrap-modal/

But you me also leave the text away and use some round buttons like this:

https://bootsnipp.com/snippets/featured/circle-button

When hover on the button it should show the last action (started/restarted etc) or the last error.
Now the API returns the error, this should be shown in the GUI as well.

API has also two endpoints for this "getFlowStatus" for latsest status and getFlowLastError (if there is no error than it returns 0. 
 		   
**1.1	Acceptance tests**

Create two flows:

      a) File to File flow
      b) SonicMQ to File flow

First should run and second should fail. First shows after starting

Green button with text "Active"

When clicking 

Last action: Starting
Status: Started succesful

Second should show

Red button with text "Inactive"

Last action: Starting
Status: Stopped after error

SomeErrorMessage

**1.2	Use case**

Pre-condition:
        - Issue 63 is solved 
        - create a service with the keys "username", "password","url". 
	- Two flows are created. The second flow uses SonicMQ as from endpoint and should used the created service.

Happy flow:
	Flow show status running with no error
Alternative path:
        Flow show other status with error
        If a flow doesn't return (say in 30 seconds) the following error should shown: "couldn't execute action. Check log fil for more details".
	
**1.3	Screen information**

Main page

**Comment by MarijaZembaFE** [comment]
Task implemented.
