### ISSUE TITLE
Service field in edit all

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#76]
**1. User story**

As user I would only select services that are available for the component type

Explanation: When editing a flow, now all services are shown in the service combobox. Only the services should be shown related to component, currently these are:

Component                             Service
SonicMQ                                 SonicMQ Connection 
SQL                                         JDBC Connection
ActiveMQ                               ActiveMQ Conncection
Kafka                                      Kafka Connection

In all other cases (for example FILE) the service should be disabled.

**1.1	Acceptance tests**

Create a dummy service for example a SonicMQ Connection. Then when creating a flow and selecting the SonicMQ endpoint should be shown.

**1.2	Use case**

Pre-condition:
	- A gateway is created
Happy flow:
	Go to edit-all (flows) page and select a service
Alternative path:
	If there are no services for a specific type, the service combox should be disabled.
	
**1.3	Screen information**

Edit-All (flows page)

**Comment by MarijaZembaFE** [comment]
Task implemented.
