### ISSUE TITLE
Links the services or headers settings from flow edit page

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#8]
**1. User story**

As a user I want to go directly from an edit page of a flow to the edit page of a header or service.

Explanation: Next the name field of (see issue 7) of service or header there should be a button "Edit header/service" with a (router) link the selcted service or header.
If the field is empty (no service or header is configured yet), go to a new page (the same if you click on button "Create header" or "Create service".).	   
	   
**1.1	Acceptance tests**

Check when user clicks on the new "Edit service" or "Edit header" button they go to the correct edit pages.

**1.2	Use case**

Pre-condition:
	- A flow is created
	- A service is created
	- A header is created
Happy flow:
	- Edit flow
	- Click on "Edit service" or "Edit header" button
	- The service or header page edit pages should open 
Alternative path:
	No
	
**1.3	Screen information**

Main page (Flow edit page)

**Comment by papicn** [comment]
Task implemented
