### ISSUE TITLE
Can not download jar file of version 4.0.3

### ISSUE THREAD

**Issue by duonglx** [assimbly/gateway#810]
Can you check Assets again? I can't see the jar file to download.
4.0.3
![image](https://github.com/assimbly/gateway/assets/9958992/305c75df-e5e2-477d-b9a6-da189fca314e)

4.0.2
![image](https://github.com/assimbly/gateway/assets/9958992/e16b5878-55a2-49f2-8066-313c5d15d343)

**Comment by skin27** [comment]
Yes, there has been a change, how assets are created recently. The complete jar doesn't get attached correctly. This will be corrected in 4.0.4

**Comment by skin27** [comment]
The jar file is attached again. 

https://github.com/assimbly/gateway/releases/tag/4.0.4

Thanks for reporting!
