### ISSUE TITLE
README.md wiki link is broken

### ISSUE THREAD

**Issue by dmitry-salmin-effem-com** [assimbly/gateway#814]
URL: https://github.com/assimbly/gateway, https://github.com/assimbly/gateway/blob/develop/README.md

Wiki link:
https://github.com/assimbly/integration/wiki - seem to be incorrect
https://github.com/assimbly/gateway/wiki - my guess for the correct link

**Comment by skin27** [comment]
You're right. It's corrected. Thanks for reporting.
