### ISSUE TITLE
Editing services or keys from Flow-Edit-All page

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#82]
**1. User story**

As a user I now can edit a service and servicekeys or header and headerkeys from their Settings pages, however when editing a service or header from a flow I can not edit the keys.

Explanation: 

Only the service and header object are shown. The keys should be editable (or alternatively the the edit (service/header) link should go to their Settings pages) 

		   
**1.1	Acceptance tests**

Edit an existing flow that uses a service and a header. Then click for both to edit them. Then all fields of the services/header including keys should be editable and saved.

**1.2	Use case**

Pre-condition:
	Flow is created with service and header
Happy flow:
	Editing the flow including service with servicekeys and header with service keys 
Alternative path:
        When a new service or header are created, also the keys fields should be available to enter	
	
**1.3	Screen information**

Main page (Flows Edit page)

**Comment by papicn** [comment]
Task implemented
