### ISSUE TITLE
Navigate endpoints with next when editing flow

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#83]
**1. User story**

As a user it should be clear where to next when creating a flow.

Explanation: 

Currently there are three tabs "from","to","error", when a user creates a flow there should be a next button (maybe instead of save) so that when finishing the "from endpoint tab" the user goes to the "to endpoint tab" and when finishing the two tabs it goes to "error endpoint tab". If all endpoints are entered the save button should become visisble.

		   
**1.1	Acceptance tests**

Create a new flow and use the next button to move to the next tab (until all endpoints are entered) and then save the flow.

**1.2	Use case**

Pre-condition:
        -
Happy flow:
	Create a flow (next --> next --> next --> save) 
Alternative path:
        Alternative a person could fill in first the error endpoint. In this case the next button should move to the first unfinished tab (for example from or if there the required fields are entered to the to tab.).  
	
**1.3	Screen information**

Main page (Flows Edit page)

**Comment by papicn** [comment]
Task implemented
