### ISSUE TITLE
Start/Pause/Stop all flows

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#84]
**1. User story**

As a user I want to stop, pause, restart, resume or start all flows with one click

Explanation: 

Currently only one flow could be started at once. There should be a button "All flows" with a dropdown with actions "Start, restart, pause, resume, stop" if the user uses this all flows should be looped and the action performed. 

Note: the API support also startAll, but it's better for error handling to start/stop/pause/restart/resume them one by one and loop them in the frontend.
		   
**1.1	Acceptance tests**

When start is chosen then loop all flows in list. If a flow has status "Stopped" then start the flow 

When stop is chosen then loop all flows in list. If a flow doesn't have status "Stopped" then stop the flow 

When restart is chosen then loop all flows in list. If a flow has the status "Started" or "Restarted" or "Resumed" then restart the flow

When pause is chosen then loop all flows in list. If a flow has the status "Started" or "Restarted" or "Resumed" then pause the flow

When resume is chosen then loop alle flows in list. If a flow has the status "Pause" then Resume the flow. 

**1.2	Use case**

Pre-condition:
        - multiple flows are created
Happy flow:
	Start/Stop/Pause/Resume/Restart all flows 
Alternative path:
        If a flow doesn't start, an error is shown.        

**1.3	Screen information**

Main page (Flows Edit page)

**Comment by MarijaZembaFE** [comment]
Task imlemented.
