### ISSUE TITLE
Read environment variable to set activemq max connections

### ISSUE THREAD

**Issue by pedrocatalao** [assimbly/gateway#863]
The environment variable `DOVETAIL_AMQ_TCP_MAXIMUM_CONNECTIONS` is already available inside the broker container. It shall be read during loading to set AMQ max connection to that value.

**Comment by skin27** [comment]
From tomorrow the maximum connections can be set on the Assimbly backend container with the environment variable:
AMQ_MAXIMUM_CONNECTIONS
I would propose the following:
xlarge --> 500
2xlarge --> 1000
4xlarge --> 1500
Note when nothing is set 500 is used.

**Comment by Hooghof** [comment]
Development on xlarge has "openConnections": 500
