### ISSUE TITLE
Broker doesn't allow JMX connection

### ISSUE THREAD

**Issue by pedrocatalao** [assimbly/gateway#864]
I'm still unable to connect to JMX.
I set the `assimbly.jmxPort=1616` in `/data/.assimbly/broker/activemq.xml` but still can't connect using `jconsole`.

Can't tell if something in the gateway-broker java layer is doing something odd.

Configuration works well with any `dovetail-activemq` image, if you start a container using for example the `dovetail-activemq:development` image, map the ports 1616 and 61616, i.e. `docker run -d -p 61616:61616 -p 1616:1616 ....` and then use `jconsole` to connect to `service:jmx:rmi:///jndi/rmi://localhost:1616/jmxrmi` it works.

Using the `gateway-broker` image, even after making sure the config is loaded i.e. run the docker container with `docker run -d -p 61616:61616 -p 1616:1616 -v /etc/kabisadata/assimbly-broker-test/broker:/data/.assimbly/broker ....` and testing different ways (hardcoded, env variable, etc) I cannot ever connect to the jmx connector.

Also tried port 1099 as suggested.

**Comment by brunovg** [comment]
I already managed to have a connection locally, between jconsole and Assimbly Broker.
Next step is to check on Management Console and Assim Broker.

**Comment by brunovg** [comment]
Also works locally on Management Console

![Image](https://github.com/user-attachments/assets/e797cd54-a69f-47ea-b01a-37cc0e971b7d)

**Comment by brunovg** [comment]
Inside the flux-console container (on development) I downloaded and used the jmxterm tool jar file.
```
java -jar jmxterm-1.0.0-uber.jar
Welcome to JMX terminal. Type "help" for available commands.

$>open service:jmx:rmi:///jndi/rmi://assimbly-broker-test:1616/jmxrmi
#Connection to service:jmx:rmi:///jndi/rmi://assimbly-broker-test:1616/jmxrmi is opened

$>beans | grep Queue
...
org.apache.activemq:brokerName=localhost,destinationName=64f88c54d6187d0132000634_test_fe48f69e-2351-4134-8265-b667ae88142f,destinationType=Queue,type=Broker
org.apache.activemq:brokerName=localhost,destinationName=64f9c1cc7eba39009e00055b_test_1a5896ee-685c-403c-a284-a368386d3a7a,destinationType=Queue,type=Broker
org.apache.activemq:brokerName=localhost,destinationName=64f9c1cc7eba39009e00055b_test_2c097757-80a9-42e7-bc87-ed2beff5988d,destinationType=Queue,type=Broker
org.apache.activemq:brokerName=localhost,destinationName=64f9c1cc7eba39009e00055b_test_719c389d-b07c-4a96-9c7b-c43cf4a961c5,destinationType=Queue,type=Broker
org.apache.activemq:brokerName=localhost,destinationName=64f9c1cc7eba39009e00055b_test_800eaa9b-3b81-4a51-98d0-5c319eed0255,destinationType=Queue,type=Broker
...
```

It seems to connect and fetch correctly the list of queues.

The problem must be on the Management Console code.

**Comment by brunovg** [comment]
PR created on MC:
https://github.com/dovetailworld/management-console/pull/9
