### ISSUE TITLE
Upgrade dependencies in 5.0.2

### ISSUE THREAD

**Issue by skin27** [assimbly/gateway#869]
Update the dependencies of following backend repositories:

- [x] 1. base
- [x] 2. runtime
- [x] 3. custom-components
- [x] 4. gateway
- [x] 5. docconverter

**Comment by skin27** [comment]
Update the next branch to the latest dependencies. This include

Spring Framework/Spring Boot
Elastic Client
Groovy
Database drivers
Some other dependencies

Note: Only Spring was upgraded with a minor version (from Spring Boot 3.3.x to 3.4.0), all others dependencies are patches. For example, from Groovy 4.0.23 to 4.0.24.

Next can be rebuilt and deployed the server.

**Comment by Hooghof** [comment]
Accepted without functional testing.
