### ISSUE TITLE
Configure multiple "To endpoints"

### ISSUE THREAD

**Issue by assimbly** [assimbly/gateway#9]
**1. User story**

As a user I can add more than one "To endpoint" to a flow.

Explanation: Currently you can at editing a flow only configure one endpoint on the "To" tab. 
The database already allows multiple "to endpoints". There should be a button to add another endpoint below the current. 
The second endpoint has the same fields as the first one. Maximum number of to endpoints should be 3.

**1.1	Acceptance tests**

Check when user add a second "To endpoint" and save the flow if the flow is properly saved to database.
When you edit the flow again all endpoints/fields should still be visible.

**1.2	Use case**

Pre-condition:
	- a flow is created
Happy flow:
	- Edit flow 
	- Add "To Endpoint"
	- Save flow 
Alternative path:
	No
	
**1.3	Screen information**

Main page (Flow edit page)

**Comment by papicn** [comment]
Task implemented
