### ISSUE TITLE
 Adding one new endpoint (EP) to multi-point flow

### ISSUE THREAD

**Issue by goran237** [assimbly/gateway#97]
**SUMMARY**
While editing the existing flow (that already consists of two end points) and trying to add a third one - results in creation of two additional endpoints (third and fourth, as a copy of third one)

**STEPS TO REPRODUCE**
1. Flows Page
2. Find and open flow that has two endpoints 
3. Edit Flow
4. Add new endpoint
5. Fill in required data for type FILE
6. Apply,Save
7. View resulting flow

**EXPECTED RESULT**
Single endpoint added

**ACTUAL RESULT**
Both endpoint and its copy are added

**ATTACHMENTS**
https://elanwave-my.sharepoint.com/:v:/p/goran_kurucev/EdztYfWqt0ZHpU_VF8oZijIBXJYYwCdxZH1sLDr8ISCzlg?e=eTpLVK

_Note: The hand symbol in the link is added automatically and breaks the link. Copy the link in browser and replace hand symbol with : v : (without spaces between them)_

**Comment by goran237** [comment]
Additional related scenario: https://elanwave-my.sharepoint.com/:v:/p/goran_kurucev/EXkQnDJCPMZDpXVLYjgNPPABY4nTIIC_mYBv8lEMHjkCrQ?e=l0Kzjx

**Comment by papicn** [comment]
Issue with duplicating toEndpoint on apply and save is solved

**Comment by goran237** [comment]
Retested, and result is OK. This issue can now be closed.
